incampusApp/urls.py
from django.urls import path
from . import views

app_name='incampusApp'

urlpatterns = [
    path('incampus_admin/', views.incampusAdminView.as_view(), name='incampus_admin'),
    path('admin_home/', views.adminHomeView.as_view(), name='admin_home'),
    path('admin_auto_register/', views.adminAutoRegisterView.as_view(), name='admin_auto_register'),
    path('admin_manual_register/', views.adminManualRegisterView.as_view(), name='admin_manual_register'),
    path('admin_edit_infomation/', views.adminEditInfomationView.as_view(), name='admin_edit_infomation'),
    path('<str:kind>/<str:user_id>/admin_edit_each_infomation/', views.adminEditEachInfomationView.as_view(), name='admin_edit_each_infomation'),
    path('<int:kind>/login/', views.LoginView.as_view(), name='login'),
    path('', views.HomeView.as_view(), name='home'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('<int:r_id>/student_data_detail/', views.StudentDateDetailView.as_view(), name='student_date_detail'),
    path('<str:u_id>/each_student_data/', views.EachStudetnDataView.as_view(), name='each_student_data'),
    path('laboratory_infomation/', views.LaboratoryInfomationView.as_view(), name='laboratory_infomation')
    #path('set_admin/', views.setAdminView.as_view(), name='set_admin')
]

incampusApp/templates/base.html
<!doctype html>
<html lang="ja">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Jekyll v3.8.5">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        {% block header %}{% endblock header %}

        <title>InCampus-{% block title %}{% endblock title %}</title>
    </head>
    <body class="bg-light">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'incampusApp:home' %}">InCampus</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <ul class="navbar-nav">
                        {% if 'id' in request.session %}
                            {% if request.session.target == 1 %}
                            <li class="nav-item">
                                <a class="nav-link" area-current="page" href="{% url 'incampusApp:laboratory_infomation' %}">研究室の設定</a>
                            </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link" area-current="page" href="{% url 'incampusApp:logout' %}">ログアウト</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" area-current="page" href="{% url 'incampusApp:login' 0 %}">ログイン(学生)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'incampusApp:login' 1 %}">ログイン(教員)</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container mb-5">
            <div class="p-3">
                {% if messages %}
                {% for message in messages %}
                {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
                {% elif message.tags == 'success' %}
                <div class="alert alert-success" role="alert">
                {% else %}
                <div class="alert alert-dark" role="alert">
                {% endif %}
                {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% block content %}{% endblock content %}
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        {% block script %}{% endblock script %}
        <footer class="footer mt-auto py-3 bg-light text-center"> <!-- fixed-bottom">-->
            <div class="container">
            <span class="text-muted">&copy;neelab</span>
            </div>
        </footer>    
    </body>
</html>

incampusApp/templates/home.html
{% extends 'base.html' %}
{% block title %}HOME{% endblock title %}
{% block header%}
{% load static %}
<link href="{% static 'c3/c3.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/style.css'%}">
<style>
.c3-ygrid-line.grid500 line {
    stroke: black;
}
.c3-ygrid-line.grid500 text {
    fill: black;
}
</style>
{% if not 'id' in request.session %}
<style>
.back-img {
    background-image: url("{% static 'img/InCampus.png' %}");
    background-position: 50% -10%;
    background-repeat: no-repeat;
    background-attachment: fixed;
}
</style>
{% endif %}
{% endblock header %}
{% block content %}
{% if 'id' in request.session %}
    {% if request.session.target == 1 %}
        <h2 class="mb-3">{{ fiscal_year }}年度 
        {% if focus_term == 0 %}
        前期
        {% else %}
        後期
        {% endif %}
        担当学生一覧</h2>
        <div id="my-container" class="mb-4" style="width: 100%; border: solid 1px black">
            <div id="all-user-graph"></div>
        </div>

        {% if  student_list != None %}
        <div class="dropdown">
            <h4><学部> コアタイム: {% if core_time.4 != None %}{{ core_time.4 }}{% endif %}~{% if core_time.5 != None %}{{ core_time.5 }}{% endif %}</h4>
            <div class="row">
                <div class="col-">
                    <table class="table table-msm table-hover text-center">
                        <thead>
                        <tr>
                            <th scope="col" style="width: 20%;">学籍番号</th>
                            <th scope="col" style="width: 20%;">氏名</th>
                            <th scope="col" style="width: 20%;">合計時間</th>
                            <th scope="col" style="width: 20%;">目標時間</th>
                            <th scope="col" style="width: 20%;">残り時間</th>
                        </tr>
                        </thead>
                            <tbody>
            {% for key, value in student_list.s_list.items %}
                            <tr data-href="{% url 'incampusApp:each_student_data' u_id=key %}">
                                <td>
                                    {{ key }}
                                </td>
                                <td>
                                    {{ value.0 }}
                                </td>
                                <td>
                                    {{ value.1 }}:{{ value.2 }}
                                </td>
                                <td>
                                    {{ value.3 }}:00
                                </td>
                                <td>
                                    {{ value.4 }}:{{ value.5 }}
                                </td>
                            </tr>
            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <h4><修士> コアタイム: {% if core_time.2 != None %}{{ core_time.2 }}{% endif %}~{% if core_time.3 != None %}{{ core_time.3 }}{% endif %}</h4>
            <div class="row">
                <div class="col-">
                    <table class="table table-sm table-hover text-center">
                        <thead>
                        <tr>
                            <th scope="col" style="width: 20%;">学籍番号</th>
                            <th scope="col" style="width: 20%;">氏名</th>
                            <th scope="col" style="width: 20%;">合計時間</th>
                            <th scope="col" style="width: 20%;">目標時間</th>
                            <th scope="col" style="width: 20%;">残り時間</th>
                        </tr>
                        </thead>
                            <tbody>
            {% for key, value in student_list.m_list.items %}
                            <tr data-href="{% url 'incampusApp:each_student_data' u_id=key %}">
                                <td>
                                    {{ key }}
                                </td>
                                <td>
                                    {{ value.0 }}
                                </td>
                                <td>
                                    {{ value.1 }}:{{ value.2 }}
                                </td>
                                <td>
                                    {{ value.3 }}:00
                                </td>
                                <td>
                                    {{ value.4 }}:{{ value.5 }}
                                </td>
                            </tr>
            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            <h4><博士> コアタイム: {% if core_time.0 != None %}{{ core_time.0 }}{% endif %}~{% if core_time.1 != None %}{{ core_time.1 }}{% endif %}</h4>
            <div class="row">
                <div class="col-">
                    <table class="table table-sm table-hover text-center">
                        <thead>
                        <tr>
                            <th scope="col" style="width: 20%;">学籍番号</th>
                            <th scope="col" style="width: 20%;">氏名</th>
                            <th scope="col" style="width: 20%;">合計時間</th>
                            <th scope="col" style="width: 20%;">目標時間</th>
                            <th scope="col" style="width: 20%;">残り時間</th>
                        </tr>
                        </thead>
                        <tbody>
            {% for key, value in student_list.d_list.items %}
                            <tr data-href="{% url 'incampusApp:each_student_data' u_id=key %}">
                                <td>
                                    {{ key }}
                                </td>
                                <td>
                                    {{ value.0 }}
                                </td>
                                <td>
                                    {{ value.1 }}:{{ value.2 }}
                                </td>
                                <td>
                                    {{ value.3 }}:00
                                </td>
                                <td>
                                    {{ value.4 }}:{{ value.5 }}
                                </td>
                            </tr>
            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        {% else %}
            <p>担当している学生のデータは存在しません</p>
        {% endif %}
    {% endif %}
{% else %}
<div class="mb-5 back-img" style="height: 500px;"></div>
<div class="row mt-5 text-center" style="bottom: 50%;">
        <div class="col">
            <a class="p-3 btn btn-outline-primary btn-lg" role="button" href="{% url 'incampusApp:login' 0 %}">学生</a>
        </div>
        <div class="col">
            
        </div>
        <div class="col">
            <a class="p-3 btn btn-outline-primary btn-lg" role="button" href="{% url 'incampusApp:login' 1 %}">教員</a>
        </div>
</div>
{% endif %}
{% endblock content %}

{% block script %}
<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/incampus.js' %}"></script>
<script src="{% static 'd3/d3.min.js' %}" charset="utf-8"></script>
<script src="{% static 'c3/c3.min.js' %}"></script>
<script>
    let ttd = JSON.parse('{{ ttd | safe}}');
    let egt = JSON.parse('{{ egt | safe }}');
    const aryMax = function (a, b) {return Math.max(a, b);}
    let maxTime = ttd.reduce(aryMax);
    ttd.sort();
    let chart = c3.generate({
      bindto: '#all-user-graph',
      size: { width: '', height: 350 }, // グラフ描画領域のサイズ
      data: {
        columns: ttd,
        type: 'bar',
        labels: true // それぞれの点に数値を表示
      },
      bar: {
          width: {
              ratio: 0.8,
          }
      },
      axis: {
        y: {
            label: '合計在室時間[h]'
        },
      },
      grid: {
        y: {
            lines: [
                {value: egt.S, class: 'grid500', text: '学部'}, 
                {value: egt.M, class: 'grid500', text: '修士'}
            ]
        }
    }
    });
    chart.axis.max(egt.S);
    setTimeout(function(){
        chart.axis.max(egt.M);
    }, 500);
    setTimeout(function() {
        chart.axis.max(maxTime);
    }, 1500);
</script>
{% endblock script %}